### ISSUE TITLE
RaspberryPi tutorial feedback

### ISSUE THREAD

**Issue by marcinag** [AVSystem/developer-zone#33]
1. Can we add links to RaspberryPi website when we introduce it?
2. In Prepare your SenseHat/GrovePi step 4, we say run the program. What should I get here to be sure that I can proceed to the next step?
3. Link to tutorial on SenseHat is not active.
4. In install Svetovid section, we have: `cd /home/pi/AVsystem/Svetovid-raspberry-client
cd ~/AVSystem/Svetovid-raspberry-client` do we need both of these lines?
5. > In file /usr/local/share/svetovid/bin/fsdm/lwm2m_object_registry.py, find the

There's number 1 again and number 1 was already above.
6. In Step 3 Register your device in Coiote DM section, numbering is again reseted
7. At the end of step 3, can we talk about the LwM2M objects that we already have? For example, can we describe FOTA process?
8. At the end of Step 4, temperature object image is broken.

**Comment by mkrawczyk-avs** [comment]
hey, thanks for the feedback and comments. I'm creating a ticket for this and will get back to it after we get the pending tasks done.
